set(_CATKIN_CURRENT_PACKAGE "push_toycar")
set(push_toycar_VERSION "0.0.0")
set(push_toycar_MAINTAINER "wenwenzju <test@todo.todo>")
set(push_toycar_PACKAGE_FORMAT "2")
set(push_toycar_BUILD_DEPENDS "roscpp" "rospy" "sensor_msgs")
set(push_toycar_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "sensor_msgs")
set(push_toycar_BUILDTOOL_DEPENDS "catkin")
set(push_toycar_BUILDTOOL_EXPORT_DEPENDS )
set(push_toycar_EXEC_DEPENDS "roscpp" "rospy" "sensor_msgs")
set(push_toycar_RUN_DEPENDS "roscpp" "rospy" "sensor_msgs")
set(push_toycar_TEST_DEPENDS )
set(push_toycar_DOC_DEPENDS )
set(push_toycar_URL_WEBSITE "")
set(push_toycar_URL_BUGTRACKER "")
set(push_toycar_URL_REPOSITORY "")
set(push_toycar_DEPRECATED "")